À la récupération du réseau, on synchronise les évaluations
betagouv/eva pull request #1063
Opened 2021-09-23 09:46 UTC by cprodhomme

2021-09-23 09:46 UTC, cprodhomme commented
![](https://github.trello.services/images/mini-trello-icon.png) [À la récupération du réseau, on synchronise les évaluations](https://trello.com/c/YVo8Je36/872-%C3%A0-la-r%C3%A9cup%C3%A9ration-du-r%C3%A9seau-on-synchronise-les-%C3%A9valuations)

2021-09-23 11:42 UTC, etienneCharignon requested changes
Il me semble qu'il y a un truc important à regarder dans mes commentaires, sur la gestion des promesse de synchronisation. Comme je ne suis pas sur eva aujourd'hui, je n'ai pas pris de temps de vérifier mes affirmations. Je fais ce commentaire pour que tu puisses avancer dessus au besoins. Sinon, on regardera ensemble demain.

2021-09-23 11:42 UTC, etienneCharignon commented on src/situations/commun/infra/synchronisateur.js
> +    if (this.enCoursDeSynchronisation === true) { return; }
C'est juste une question de style mais vraiment je préfèrerait qu'on écrive `if (this.enCoursDeSynchronisation) { return; }`

2021-09-23 11:42 UTC, etienneCharignon commented on src/situations/commun/infra/synchronisateur.js
> +          this.registreUtilisateur.enregistreUtilisateurEnLocal(utilisateur, idClient);
`enregistreContact()` et `creeEvaluation()` renvoient toutes les deux une promesse. Il faut ajouter le catch pour traiter l'erreur réseau éventuelle et décider ce qu'on fait dans ce cas là. Sinon il me semble que l'erreur risque d'être passée sous silence. Mais surtout, je ne sais pas ce qu'on fait. Est-ce qu'on arrête de tout synchroniser ? Est-ce qu'on ré-essaye ? Je crois qu'on va peut-être traiter ce cas là plus tard…  Si c'est ce qui est envisagé alors je ferais bien juste un `.catch((err) => { console.err(err) }`

2021-09-23 11:42 UTC, etienneCharignon commented on src/situations/commun/infra/synchronisateur.js
> +    }
Je ne crois pas que ça marche. Il faut en réalité récupérer toutes les promesses dans un tableau et faire un `Promise.all(tableaudespromesses).finaly()`

2021-09-24 08:20 UTC, cprodhomme commented on src/situations/commun/infra/synchronisateur.js
> +    }
Je ne sais pas ! j'imagine que tu as raison :)

2021-09-24 08:22 UTC, cprodhomme commented on src/situations/commun/infra/synchronisateur.js
> +          this.registreUtilisateur.enregistreUtilisateurEnLocal(utilisateur, idClient);
Selon, on ne fait rien si on arrive pas à le synchro et on retente à la prochaine récupération du réseau

2021-09-24 08:24 UTC, cprodhomme commented
Je me pose la question aussi si on doit lancer la synchronisation au début quand on arrive sur la page si on a du réseau

2021-09-24 14:32 UTC, etienneCharignon approved these changes

2021-09-24 14:41 UTC, merged