996 prise en main les mini tutoriels
betagouv/eva pull request #1182
Opened 2022-03-14 15:55 UTC by cprodhomme

2022-03-14 15:57 UTC, cprodhomme commented
![](https://github.trello.services/images/mini-trello-icon.png) [Prise en Main : les mini tutoriels](https://trello.com/c/yRnMjIDT/996-prise-en-main-les-mini-tutoriels)

2022-03-14 15:58 UTC, cprodhomme commented
Je pense qu'il manque pas mal de test sur cette PR

2022-03-15 06:59 UTC, etienneCharignon commented on src/situations/commun/vues/video_consigne.vue
> +    <source :src="source" type="video/mp4">
mp4 ! c'est chaud non ? Est-ce qu'on ne serait pas plus tranquille avec des gifs animés en terme de compatibilité ? Et on n'a pas vraiment besoins de diffuser des films si ? (on aura pas a afficher une barre de lecture, ni la possibilité de faire play/pause…)

2022-03-15 09:44 UTC, cprodhomme commented on src/situations/commun/vues/video_consigne.vue
> +    <source :src="source" type="video/mp4">
Cela fait partie de la discussion que j'ai eu avec Benjamin en commentaire du [ticket](https://trello.com/c/yRnMjIDT/996-prise-en-main-les-mini-tutoriels) 
Le Mp4 est beaucoup plus léger qu'un gif :)

2022-03-18 17:47 UTC, etienneCharignon commented
J'ai cru que j'y était mais je viens de trouver un loup : 
Dans `src/situations/plan_de_la_ville/data/defis.js` on utilise `nom_technique`
Mais dans `src/situations/objets_trouves/data/apps.js` on utilise `nomTechnique`

😢

Je laisse ça pour lundi

2022-03-18 17:48 UTC, etienneCharignon requested changes
Résoudre le problème de nommage de la propriété nom_technique entre plan de la ville et objets trouvés

2022-03-21 09:31 UTC, etienneCharignon commented on src/situations/commun/vues/video_consigne.vue
> +    <source :src="source" type="video/mp4">
ok

2022-03-21 11:31 UTC, etienneCharignon approved these changes
Ok avec le commit supplémentaire

2022-03-21 11:31 UTC, merged